#!/bin/sh
# deploy the current plugin to vim repository 
# credit julien muetton <julien_muetton@carpe-hora.com>

# read current file real path
SCRIPT_PATH=`readlink -f $0` ;
REPONAME=`dirname $SCRIPT_PATH`;
SCRIPTNAME=`echo "$SCRIPT_PATH" | sed "s:^.*/\([^\/]*\)$:\1:"`

ls $REPONAME | grep -v $SCRIPTNAME | while read file 
do
  cp -R $REPONAME/$file ~/.vim
done;
