#!/bin/sh
# deploy the current plugin to vim repository 
# credit julien muetton <julien_muetton@carpe-hora.com>

#current path as argument ?
REPONAME="$1";
if [ -z "$REPONAME" ]
then
  REPONAME=`dirname $0`
fi

ls $REPONAME | grep -v "vim-snippets-" | grep -v "README" | while read file 
do
  cp -R $REPONAME/$file ~/.vim
done;
